version: '3'

vars:
  IMAGE_NAME: perf-lab
  IMAGE: olmigar/{{.IMAGE_NAME}}
  TAG: '{{.TAG | default "v1"}}'
  LOCAL_PORT: 8080
  SVC_NAME: perf-lab
  GIT_SHA:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"

tasks:
  build:
    desc: Build the Go binary
    cmds:
      - go build -ldflags="-X main.gitSHA={{.GIT_SHA}}" -o server ./cmd/api

  run:
    desc: Run the server locally
    cmds:
      - go run ./cmd/api

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  docker-build:
    desc: Build Docker image
    cmds:
      - docker build --build-arg GIT_SHA={{.GIT_SHA}} -t {{.IMAGE}}:{{.TAG}} .

  docker-push:
    desc: Push Docker image to DockerHub
    cmds:
      - docker push {{.IMAGE}}:{{.TAG}}

  docker-build-push:
    desc: Build and push Docker image to DockerHub
    cmds:
      - task: docker-build
      - task: docker-push
