apiVersion: v1
kind: Service
metadata:
  name: perf-lab
  labels:
    app: perf-lab
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: perf-lab
