apiVersion: apps/v1
kind: Deployment
metadata:
  name: victim-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victim-api
  template:
    metadata:
      labels:
        app: victim-api
    spec:
      nodeSelector:
        workload: noisy-node
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "noisy-node"
        effect: "NoSchedule"
      containers:
      - name: api
        image: hashicorp/http-echo:latest
        args: ["-text=hello-from-victim"]
        ports:
        - containerPort: 5678
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
